### ISSUE TITLE
Feature:  Disclaimer: As a Product Owner I can clearly state that this site is not giving financial advice so that nobody sues me

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/FLIT_FP_Merge#1]
EPIC:  DOCUMENTATION & STRUCTURE

As a **Product Owner** I want to **clearly state that this site is not giving financal advice and is for entertainment purposes only** to achieve **clear expectations at the outset for site users**  
As **User*  I want to **clearly understand that this site is not going to solve all my financial problems** to **avoid my life going down the swanney**

### Assumptions or Pre-Requisites:
* This applies both to placeholder site and to final FLIT.ie site
*
*

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [ ] Must
- [ ] Must

### Tasks

- [x] Task1 Determine appropriate text
- [x] Task2 Find a sensible place to put this (bottom of landing page?)
- [ ] Task3 Add it into FLIT_placeholder
- [x] Task4 Add it into FLIT_FP Merge

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by DeeMcCart** [comment]
Reviewed 09/11/24 (this is work done in Octoer 2024) - disclaimer has been added to footer.
OK to close out this issue.

![Image](https://github.com/user-attachments/assets/78ad9567-0ad4-4af9-a0ea-c49db881a6f9)

Not added into FLIT placeholder 0 not required
