### ISSUE TITLE
User Story:  Front-end Admin view to edit articles

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/FLIT_FP_Merge#10]
EPIC:  ADMIN

As an **administrator** I can **edit and update articles via a front-end** so that **I don't need to use a separate URL, and all changes can be administered from one logical view**
### Acceptance Criteria
*  Sysadmin dropdown to CRUD articles
*  

### Tasks
- [x] Task1 Add new article (including summernote)
- [x] Task2 Preview article
- [ ] Task3 Edit existing article (including summernoteO
- [ ] Task4 Delete existing article

**Comment by DeeMcCart** [comment]
Done 12/10/24 With help of Stephen can now C add R preview (even if not yet published) U edit D delete articles from a maintenance window.  Usability issue noted in separate comments below:

**Comment by DeeMcCart** [comment]
Maintenance pulldown

![Image](https://github.com/user-attachments/assets/38ce47bc-bc3f-4c24-9a52-52299b518bb7)
