### ISSUE TITLE
User Story:  Quiz

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/FLIT_FP_Merge#11]
EPIC:  <epic>

As a **user** I can **perform a quiz** so that **I get feedback on my knowledge**
As an **administrator** I can design quiz(es) to fit into the structure of the learrning e.g. article1, 2, 3, quiz 1, article4, quiz2, etc

### Assumptions:
The quiz could be inserted into material by the administrator

### Acceptance Criteria
* Multi-choice quiz can be designed 
* User receives results of their multi-choice quiz

### Tasks

- [ ] Task1 Decide how this will be designed?  Django module with text question and 4 possible answer pairs
- [ ] Task2 How will sccoring work - will there be some sort of runing total score for a user?  Will scoring be calculated by model?  By topic?  Will scoring be preserved from one instance to the next?
- [ ] Task3 Will it be mmandatory to give an anwwer to a quiz or will some quizzes allow 'skip'?
- [ ] Task4

![image](https://github.com/user-attachments/assets/8af58724-602e-4b23-bd5c-91915bd53618)
